apptkt/urls.py
from django.conf.urls import url
from apptkt import views

app_name = 'apptkt'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<company_id>[0-9]+)/$', views.detail, name="detail"),
]

tkttest/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^company/', include('apptkt.urls', namespace="company")),
]

apptkt/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=100)
    sector = models.CharField(max_length=100)
    siren = models.IntegerField()

    def __str__(self):
        return "{} company (sector: {}, siren: {})".format(self.name, self.sector, self.siren)


class Result(models.Model):
    company = models.ForeignKey('Company', on_delete=models.CASCADE)
    ca = models.IntegerField()
    margin = models.IntegerField()
    ebitda = models.IntegerField()
    loss = models.IntegerField()
    year = models.IntegerField()

    def __str__(self):
        return "{} {} results >>> ca: {}, margin: {}, ebitda: {}, loss: {}".format(self.company.name, self.year,
                                                                                   self.ca, self.margin, self.ebitda,
                                                                                   self.loss)

apptkt/views.py
from __future__ import unicode_literals

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render
from apptkt.models import Company


def index(request):
    companies = Company.objects.order_by("name")
    """ Pagination - Show 120 companies per page """
    paginator = Paginator(companies, 120)
    page = request.GET.get('page')
    try:
        companies = paginator.page(page)
    except PageNotAnInteger:
        companies = paginator.page(1)
    except EmptyPage:
        companies = paginator.page(paginator.num_pages)

    context = {'companies': companies, }
    return render(request, 'index.html', context)


def detail(request, company_id):
    company = get_object_or_404(Company, pk=company_id)
    results = company.result_set.order_by("year")

    context = {'company': company, 'results': results, }
    return render(request, 'detail.html', context)

apptkt/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="../../favicon.ico">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Django test -{% block title %}{% endblock title %}</title>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'company:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown link
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>


      {% block content %}
      {% endblock content %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

apptkt/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ company.name|title }} {% endblock title %}

{% block content %}
<div class="container">
    <div class="container p-4">
       <h1>{{ company.name|title }} company</h1>
    </div>
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col"> </th>
                {% for result in results %}
                    <th scope="col">{{ result.year }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">CA</th>
                {% for result in results %}
                    <td>{{ result.ca }}$</td>
                <{% endfor %}
            </tr>
            <tr>
                <th scope="row">Margin</th>
                {% for result in results %}
                    <td>{{ result.margin }}$</td>
                <{% endfor %}
            </tr>
            <tr>
                <th scope="row">Ebitda</th>
                {% for result in results %}
                    <td>{{ result.ebitda }}$</td>
                <{% endfor %}
            </tr>
            <tr>
                <th scope="row">Loss</th>
                {% for result in results %}
                    <td>{{ result.loss }}$</td>
                <{% endfor %}
            </tr>
        </tbody>
    </table>
    <a href="{% url 'company:index' %}" class="btn btn-secondary stretched-link">Back to companies</a>
</div>

{% endblock content %}

apptkt/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %} Companies {% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="container p-4">
        <h1>Companies</h1>
    </div>
    <div class="cards-company">
        {% for company in companies %}
                <div class="card m-2" style="width: 13rem; height: 21rem;">
                    {% if company.sector == "Services" %}
                        <img src="https://cdn.pixabay.com/photo/2014/10/22/17/50/bar-498420_1280.jpg" class="card-img-top" alt="">
                    {% elif company.sector == "Retail" %}
                        <img src="https://cdn.pixabay.com/photo/2015/10/12/15/18/clothing-store-984396_1280.jpg" class="card-img-top" alt="">
                    {% elif company.sector == "Luxury" %}
                        <img src="https://cdn.pixabay.com/photo/2014/04/05/11/40/diamond-316610_1280.jpg" class="card-img-top" alt="">
                    {% elif company.sector == "Energy" %}
                        <img src="https://cdn.pixabay.com/photo/2017/01/18/10/17/renewable-1989416_1280.jpg" class="card-img-top" alt="">
                    {% elif company.sector == "Electronic" %}
                        <img src="https://cdn.pixabay.com/photo/2015/02/24/14/37/technical-647488_1280.jpg" class="card-img-top" alt="">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ company.name }}</h5>
                        <p class="card-text">Service: {{company.sector}}</p>
                        <a href="{% url 'company:detail' company.pk %}" class="btn btn-secondary">see results</a>
                    </div>
                </div>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="step-links">
        {% if companies.has_previous %}
            <a href="?page={{ companies.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ companies.number }} of {{ companies.paginator.num_pages }}.
        </span>

        {% if companies.has_next %}
            <a href="?page={{ companies.next_page_number }}">next</a>
        {% endif %}
        </span>
    </div>
</div>

{% endblock content %}